<?php

return $languages = [
['Abkhaz', 'аҧсуа бызшәа, аҧсшәа', 'ab'],
['Afar', 'Afaraf', 'aa'],
['Afrikaans', 'Afrikaans', 'af'],
['Akan', 'Akan', 'ak'],
['Albanian', 'gjuha shqipe', 'sq'],
['Amharic', 'አማርኛ', 'am'],
['Arabic', 'العربية', 'ar'],
['Aragonese', 'aragonés', 'an'],
['Armenian', 'Հայերեն', 'hy'],
['Assamese', 'অসমীয়া', 'as'],
['Avaric', 'авар мацӀ, магӀарул мацӀ', 'av'],
['Avestan', 'avesta', 'ae'],
['Aymara', 'aymar aru', 'ay'],
['Azerbaijani', 'azərbaycan dili', 'az'],
['Bambara', 'bamanankan', 'bm'],
['Bashkir', 'башҡорт теле', 'ba'],
['Basque', 'euskara, euskera', 'eu'],
['Belarusian', 'беларуская мова', 'be'],
['Bengali; Bangla', 'বাংলা', 'bn'],
['Bihari', 'भोजपुरी', 'bh'],
['Bislama', 'Bislama', 'bi'],
['Bosnian', 'bosanski jezik', 'bs'],
['Breton', 'brezhoneg', 'br'],
['Bulgarian', 'български език', 'bg'],
['Burmese', 'ဗမာစာ', 'my'],
['Catalan; Valencian', 'català, valencià', 'ca'],
['Chamorro', 'Chamoru', 'ch'],
['Chechen', 'нохчийн мотт', 'ce'],
['Chichewa; Chewa; Nyanja', 'chiCheŵa, chinyanja', 'ny'],
['Chinese Simplified', '', 'zh-cn'],
['Chinese Traditional', '', 'zh-tw'],
['Chuvash', 'чӑваш чӗлхи', 'cv'],
['Cornish', 'Kernewek', 'kw'],
['Corsican', 'corsu, lingua corsa', 'co'],
['Cree', 'ᓀᐦᐃᔭᐍᐏᐣ', 'cr'],
['Croatian', 'hrvatski jezik', 'hr'],
['Czech', 'čeština, český jazyk', 'cs'],
['Danish', 'dansk', 'da'],
['Divehi; Dhivehi; Maldivian;', 'ދިވެހި', 'dv'],
['Dutch', 'Nederlands, Vlaams', 'nl'],
['Dzongkha', 'རྫོང་ཁ', 'dz'],
['English', 'English', 'en'],
['Esperanto', 'Esperanto', 'eo'],
['Estonian', 'eesti, eesti keel', 'et'],
['Ewe', 'Eʋegbe', 'ee'],
['Faroese', 'føroyskt', 'fo'],
['Fijian', 'vosa Vakaviti', 'fj'],
['Finnish', 'suomi, suomen kieli', 'fi'],
['French', 'français, langue française', 'fr'],
['Fula; Fulah; Pulaar; Pular', 'Fulfulde, Pulaar, Pular', 'ff'],
['Galician', 'galego', 'gl'],
['Georgian', 'ქართული', 'ka'],
['German', 'Deutsch', 'de'],
['Greek', 'ελληνικά', 'el'],
['Guaraní', 'Avañe\'ẽ', 'gn'],
['Gujarati', 'ગુજરાતી', 'gu'],
['Haitian', 'Kreyòl ayisyen', 'ht'],
['Hausa', 'Hausa, هَوُسَ', 'ha'],
['Hebrew (modern)', 'עברית', 'he'],
['Herero', 'Otjiherero', 'hz'],
['Hindi', 'हिन्दी, हिंदी', 'hi'],
['Hiri Motu', 'Hiri Motu', 'ho'],
['Hungarian', 'magyar', 'hu'],
['Interlingua', 'Interlingua', 'ia'],
['Indonesian', 'Bahasa Indonesia', 'id'],
['Interlingue', 'Originally called Occidental; then Interlingue after WWII', 'ie'],
['Irish', 'Gaeilge', 'ga'],
['Igbo', 'Asụsụ Igbo', 'ig'],
['Inupiaq', 'Iñupiaq, Iñupiatun', 'ik'],
['Ido', 'Ido', 'io'],
['Icelandic', 'Íslenska', 'is'],
['Italian', 'italiano', 'it'],
['Inuktitut', 'ᐃᓄᒃᑎᑐᑦ', 'iu'],
['Japanese', '日本語 (にほんご)', 'ja'],
['Javanese', 'basa Jawa', 'jv'],
['Kalaallisut, Greenlandic', 'kalaallisut, kalaallit oqaasii', 'kl'],
['Kannada', 'ಕನ್ನಡ', 'kn'],
['Kanuri', 'Kanuri', 'kr'],
['Kashmiri', 'कश्मीरी, كشميري‎', 'ks'],
['Kazakh', 'қазақ тілі', 'kk'],
['Khmer', 'ខ្មែរ, ខេមរភាសា, ភាសាខ្មែរ', 'km'],
['Kikuyu, Gikuyu', 'Gĩkũyũ', 'ki'],
['Kinyarwanda', 'Ikinyarwanda', 'rw'],
['Kyrgyz', 'Кыргызча, Кыргыз тили', 'ky'],
['Komi', 'коми кыв', 'kv'],
['Kongo', 'KiKongo', 'kg'],
['Korean', '한국어 (韓國語), 조선어 (朝鮮語)', 'ko'],
['Kurdish', 'Kurdî, كوردی‎', 'ku'],
['Kwanyama, Kuanyama', 'Kuanyama', 'kj'],
['Latin', 'latine, lingua latina', 'la'],
['Luxembourgish', 'Lëtzebuergesch', 'lb'],
['Ganda', 'Luganda', 'lg'],
['Limburgish, Limburgan, Limburger', 'Limburgs', 'li'],
['Lingala', 'Lingála', 'ln'],
['Lao', 'ພາສາລາວ', 'lo'],
['Lithuanian', 'lietuvių kalba', 'lt'],
['Luba-Katanga', 'Tshiluba', 'lu'],
['Latvian', 'latviešu valoda', 'lv'],
['Manx', 'Gaelg, Gailck', 'gv'],
['Macedonian', 'македонски јазик', 'mk'],
['Malagasy', 'fiteny malagasy', 'mg'],
['Malay', 'bahasa Melayu, بهاس ملايو‎', 'ms'],
['Malayalam', 'മലയാളം', 'ml'],
['Maltese', 'Malti', 'mt'],
['Māori', 'te reo Māori', 'mi'],
['Marathi (Marāṭhī)', 'मराठी', 'mr'],
['Marshallese', 'Kajin M̧ajeļ', 'mh'],
['Mongolian', 'монгол', 'mn'],
['Nauru', 'Ekakairũ Naoero', 'na'],
['Navajo, Navaho', 'Diné bizaad, Dinékʼehǰí', 'nv'],
['Norwegian Bokmål', 'Norsk bokmål', 'nb'],
['North Ndebele', 'isiNdebele', 'nd'],
['Nepali', 'नेपाली', 'ne'],
['Ndonga', 'Owambo', 'ng'],
['Norwegian Nynorsk', 'Norsk nynorsk', 'nn'],
['Norwegian', 'Norsk', 'no'],
['Nuosu', 'ꆈꌠ꒿ Nuosuhxop', 'ii'],
['South Ndebele', 'isiNdebele', 'nr'],
['Occitan', 'occitan, lenga d\'òc', 'oc'],
['Ojibwe, Ojibwa', 'ᐊᓂᔑᓈᐯᒧᐎᓐ', 'oj'],
['Old Church Slavonic, Church Slavic, Church Slavonic, Old Bulgarian, Old Slavonic', 'ѩзыкъ словѣньскъ', 'cu'],
['Oromo', 'Afaan Oromoo', 'om'],
['Oriya', 'ଓଡ଼ିଆ', 'or'],
['Ossetian, Ossetic', 'ирон æвзаг', 'os'],
['Panjabi, Punjabi', 'ਪੰਜਾਬੀ, پنجابی‎', 'pa'],
['Pāli', 'पाऴि', 'pi'],
['Persian', 'فارسی', 'fa'],
['Polish', 'język polski, polszczyzna', 'pl'],
['Pashto, Pushto', 'پښتو', 'ps'],
['Portuguese', 'português', 'pt'],
['Quechua', 'Runa Simi, Kichwa', 'qu'],
['Romansh', 'rumantsch grischun', 'rm'],
['Kirundi', 'Ikirundi', 'rn'],
['Romanian', 'limba română', 'ro'],
['Russian', 'русский язык', 'ru'],
['Sanskrit (Saṁskṛta)', 'संस्कृतम्', 'sa'],
['Sardinian', 'sardu', 'sc'],
['Sindhi', 'सिन्धी, سنڌي، سندھی‎', 'sd'],
['Northern Sami', 'Davvisámegiella', 'se'],
['Samoan', 'gagana fa\'a Samoa', 'sm'],
['Sango', 'yângâ tî sängö', 'sg'],
['Serbian', 'српски језик', 'sr'],
['Scottish Gaelic; Gaelic', 'Gàidhlig', 'gd'],
['Shona', 'chiShona', 'sn'],
['Sinhala, Sinhalese', 'සිංහල', 'si'],
['Slovak', 'slovenčina, slovenský jazyk', 'sk'],
['Slovene', 'slovenski jezik, slovenščina', 'sl'],
['Somali', 'Soomaaliga, af Soomaali', 'so'],
['Southern Sotho', 'Sesotho', 'st'],
['Spanish', 'español, castellano', 'es'],
['Sundanese', 'Basa Sunda', 'su'],
['Swahili', 'Kiswahili', 'sw'],
['Swati', 'SiSwati', 'ss'],
['Swedish', 'Svenska', 'sv'],
['Tamil', 'தமிழ்', 'ta'],
['Telugu', 'తెలుగు', 'te'],
['Tajik', 'тоҷикӣ, toğikī, تاجیکی‎', 'tg'],
['Thai', 'ไทย', 'th'],
['Tigrinya', 'ትግርኛ', 'ti'],
['Tibetan', 'བོད་ཡིག', 'bo'],
['Turkmen', 'Türkmen, Түркмен', 'tk'],
['Tagalog', 'Wikang Tagalog, ᜏᜒᜃᜅ᜔ ᜆᜄᜎᜓᜄ᜔', 'tl'],
['Tswana', 'Setswana', 'tn'],
['Tonga (Tonga Islands)', 'faka Tonga', 'to'],
['Turkish', 'Türkçe', 'tr'],
['Tsonga', 'Xitsonga', 'ts'],
['Tatar', 'татар теле, tatar tele', 'tt'],
['Twi', 'Twi', 'tw'],
['Tahitian', 'Reo Tahiti', 'ty'],
['Uighur, Uyghur', 'Uyƣurqə, ئۇيغۇرچە‎', 'ug'],
['Ukrainian', 'українська мова', 'uk'],
['Urdu', 'اردو', 'ur'],
['Uzbek', 'O\'zbek, Ўзбек, أۇزبېك‎', 'uz'],
['Venda', 'Tshivenḓa', 've'],
['Vietnamese', 'Tiếng Việt', 'vi'],
['Volapük', 'Volapük', 'vo'],
['Walloon', 'walon', 'wa'],
['Welsh', 'Cymraeg', 'cy'],
['Wolof', 'Wollof', 'wo'],
['Western Frisian', 'Frysk', 'fy'],
['Xhosa', 'isiXhosa', 'xh'],
['Yiddish', 'ייִדיש', 'yi'],
['Yoruba', 'Yorùbá', 'yo'],
['Zhuang, Chuang', 'Saɯ cueŋƅ, Saw cuengh', 'za'],
['Zulu', 'isiZulu', 'zu']
];
